version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
networks :
    appnet:
        name: docker-compose_appnet
        driver: bridge
