version: "3.9"
services:
  app:
    build:
      dockerfile: Docker/Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    networks:
      - appnet
    ports:
      - "3030:3030"
networks :
    appnet:
        name: docker-compose_appnet
        driver: bridge
